# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1eab1f02458c92a3afca374174f45f7fe261427f352e66ecd274aa3582a60076ce2e65c5d194f4f3ed3b67a3cd2e05ad424bb047d3635091f989a7ba8cc8408e

test:
  secret_key_base: 69acf9358a385ec365683878adc7fd52a67fc7ac1842e5a3d311c9b3711ceb9d2bd351c7e8c8e1ff2fcd3430c3c0912d7f8cd11f8e18fa1c221c80b8ad0979e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
